### ISSUE TITLE
Can teleport the radar back

### ISSUE THREAD

**Issue by MrAngularVelocity** [MrHydralisk/Lethal-Company-Enhanced-Radar-Booster#10]
Just noticing that teleporting the radar back plays the animation, but does not do anything to the radar scanner.
The inverse teleporter works fine with this.

**Comment by ManaStar** [comment]
Can confirm that this is the case when paired with AdvancedCompany!

**Comment by MrHydralisk** [comment]
1. Config file settings, logs and info whenever you was the host would be nice to have, when repoting of issue. 
2. Is it happening only to teleporting it back, but not to inverse teleporting.
3. If it only not working due to AdvancedCompany, then probably better to report it to AdvancedCompany mod then, cause it doesn't seems to have open source code. So it really problematic to find what causing it in AC mod on my side without info from AC dev.
