### ISSUE TITLE
[Bug/Compat] Radar Booster's location isn't specified after teleportation

### ISSUE THREAD

**Issue by zndrmn** [MrHydralisk/Lethal-Company-Enhanced-Radar-Booster#18]
This mainly affects [OpenBodyCams](https://github.com/Zaggy1024/LC_OpenBodyCams) radar booster camera because it doesn't know if it's still within the ship or inside the interior which causes the camera to never reenable itself after teleportation.

Also I would like to add that the radar booster teleports back to the ship instantly when it should be delayed by a couple of seconds. Just like when a player is getting teleported back from the interior.

First reported here https://github.com/Zaggy1024/LC_OpenBodyCams/issues/37, there's also some extra info about the problem there.

> https://github.com/Zaggy1024/LC_OpenBodyCams/issues/37#issuecomment-2071915402

**Comment by MrHydralisk** [comment]
1) Ig, if that mod check RadarBooster flag of being on ship, but atm I not really sure what code function needed to be added to change that flag. Will see what can be done, once I will revisit Lethal Company.

2) While teleporting with delay might fit better, that will require a lot of additional synchronizing, so that's why I went with safer way of sync with instant teleport.

**Comment by MrHydralisk** [comment]
Fixed
